/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package uas_pbo;


import java.awt.Color;
import uas_pbo.Koneksi;
import uas_pbo.Main_Utama;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author NHQE1
 */
public class Form_Login extends javax.swing.JFrame {
    int xx, xy;

    /**
     * Creates new form Form_Create
     */
    public Form_Login() {
        initComponents();
    }
    
    void bersih(){
        
        p_create.setText("Log in");
        p_email.setText("Email or Number phone");
        btn_login.setText("Create Account");
        p_pass.setText("Password");
        p_google.setText("Sign up with Google");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jTextField1 = new javax.swing.JTextField();
        p_email = new javax.swing.JTextField();
        btn_login = new javax.swing.JButton();
        p_google = new javax.swing.JButton();
        jTextField6 = new javax.swing.JTextField();
        p_create = new javax.swing.JButton();
        p_pass = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(241, 229, 209));
        jPanel1.setPreferredSize(new java.awt.Dimension(914, 552));

        jTextField1.setBackground(new java.awt.Color(241, 229, 209));
        jTextField1.setFont(new java.awt.Font("JetBrains Mono", 1, 24)); // NOI18N
        jTextField1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField1.setText("LOGIN");
        jTextField1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jTextField1.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jTextField1.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        p_email.setBackground(new java.awt.Color(241, 229, 209));
        p_email.setFont(new java.awt.Font("JetBrains Mono", 0, 14)); // NOI18N
        p_email.setText("Email or Phone number");
        p_email.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                p_emailFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                p_emailFocusLost(evt);
            }
        });
        p_email.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                p_emailActionPerformed(evt);
            }
        });

        btn_login.setBackground(new java.awt.Color(219, 68, 68));
        btn_login.setFont(new java.awt.Font("JetBrains Mono", 0, 14)); // NOI18N
        btn_login.setForeground(new java.awt.Color(255, 255, 255));
        btn_login.setText("Login");
        btn_login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_loginActionPerformed(evt);
            }
        });

        p_google.setFont(new java.awt.Font("JetBrains Mono", 0, 14)); // NOI18N
        p_google.setText("Sign up with Google");
        p_google.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                p_googleActionPerformed(evt);
            }
        });

        jTextField6.setBackground(new java.awt.Color(241, 229, 209));
        jTextField6.setFont(new java.awt.Font("JetBrains Mono", 0, 12)); // NOI18N
        jTextField6.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField6.setText("already have account?");
        jTextField6.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jTextField6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField6ActionPerformed(evt);
            }
        });

        p_create.setFont(new java.awt.Font("JetBrains Mono", 0, 14)); // NOI18N
        p_create.setText("create");
        p_create.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                p_createMouseClicked(evt);
            }
        });
        p_create.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                p_createActionPerformed(evt);
            }
        });

        p_pass.setText("jPasswordField1");
        p_pass.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                p_passFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                p_passFocusLost(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(79, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(83, 83, 83))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(p_google, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btn_login, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(p_email, javax.swing.GroupLayout.DEFAULT_SIZE, 314, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(p_create))
                            .addComponent(p_pass))
                        .addGap(57, 57, 57))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47)
                .addComponent(p_email, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(p_pass, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(btn_login, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(p_google, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(p_create))
                .addContainerGap(156, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 450, 490));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void p_emailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_p_emailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_p_emailActionPerformed

    private void p_createActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_p_createActionPerformed
        Form_Create Fl = new Form_Create();
        Fl.show();
        
        dispose();
    }//GEN-LAST:event_p_createActionPerformed

    private void p_emailFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_p_emailFocusGained
        String email=p_email.getText();
        if(email.equals("Email or Phone number")){
            p_email.setText("");
        }
    }//GEN-LAST:event_p_emailFocusGained

    private void p_emailFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_p_emailFocusLost
        String email=p_email.getText();
        if(email.equals("")||email.equals("Email or Phone number")){
            p_email.setText("Email or Phone number");
        }
    }//GEN-LAST:event_p_emailFocusLost

    private void p_googleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_p_googleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_p_googleActionPerformed

    private void jTextField6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField6ActionPerformed

    private void p_createMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_p_createMouseClicked
        
    }//GEN-LAST:event_p_createMouseClicked

    private void btn_loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_loginActionPerformed
        Main_Utama MU = new Main_Utama();
        MU.show();
        
        dispose();
        
        try{
            Connection c = Koneksi.getKoneksi();
            Statement s = c.createStatement();
            
            String sql = "SELECT * FROM User WHERE nama='" + p_email.getText()
                    +"' and Password='"+ p_pass.getText() + "'";
            ResultSet r = s.executeQuery(sql);
            
            if (r.next()){
                JOptionPane.showMessageDialog(null, "Login Successfully");
                this.dispose(); //close the form
            }else{
                JOptionPane.showMessageDialog(null, "Wrong Username or Password");
                p_pass.requestFocus();
            }
        }catch(SQLException e){
            System.out.println("error");
        }
    
        
        
    }//GEN-LAST:event_btn_loginActionPerformed

    private void p_passFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_p_passFocusGained

        if(String.valueOf(p_pass.getPassword()).equals("Password")){
            p_pass.setText("");
            p_pass.setForeground(Color.BLACK);
        }
    }//GEN-LAST:event_p_passFocusGained

    private void p_passFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_p_passFocusLost
        
    }//GEN-LAST:event_p_passFocusLost

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Form_Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Form_Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Form_Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Form_Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Form_Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_login;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JButton p_create;
    private javax.swing.JTextField p_email;
    private javax.swing.JButton p_google;
    private javax.swing.JPasswordField p_pass;
    // End of variables declaration//GEN-END:variables
}


